source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'
use_frameworks! :linkage => :static
inhibit_all_warnings!

install! 'cocoapods',
:generate_multiple_pod_projects => true,
:incremental_installation => true

def module_dependency_pod
  #insert pod here if needed
  pod 'DiaryCoordinator', :path => '../DiaryCoordinator'
  pod 'DiaryFoundation', :path => '../DiaryFoundation'
end

target 'SandboxApp' do
  module_dependency_pod

  pod 'Settings', :path => '.'
end

target 'Settings' do
  module_dependency_pod

  target 'SettingsTests' do
    
  end
end
